"""add login lockout and last_login fields to users

Revision ID: 963abc2ac92d
Revises: 163d07db3728
Create Date: 2026-09-29 01:21:52.275201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '963abc2ac92d'
down_revision = '163d07db3728'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('failed_login_count', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('locked_until', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_login_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_login_at')
        batch_op.drop_column('locked_until')
        batch_op.drop_column('failed_login_count')

    # ### end Alembic commands ###
