"""add admin approval fields to users

Revision ID: f3fb0005781d
Revises: 963abc2ac92d
Create Date: 2026-09-30 00:17:16.261681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3fb0005781d'
down_revision = '963abc2ac92d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purpose', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), server_default=sa.false(), nullable=False))
        batch_op.add_column(sa.Column('approval_status', sa.String(length=20), server_default='pending', nullable=False))
        batch_op.add_column(sa.Column('approval_decided_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('approved_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rejection_reason', sa.String(length=500), nullable=True))
        batch_op.create_foreign_key('fk_users_approved_by_id_users', 'users', ['approved_by_id'], ['id'])

    # 이번 반영 이전에 가입해 이미 사용 중인 계정은 재승인 없이 사용할 수 있도록 승인 상태로 둔다.
    op.execute(sa.text("UPDATE users SET approval_status = 'approved'"))


def downgrade():
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_approved_by_id_users', type_='foreignkey')
        batch_op.drop_column('rejection_reason')
        batch_op.drop_column('approved_by_id')
        batch_op.drop_column('approval_decided_at')
        batch_op.drop_column('approval_status')
        batch_op.drop_column('is_admin')
        batch_op.drop_column('purpose')

    # ### end Alembic commands ###
